name: label-master-pr
run-name: Label Master PR as master
on: 
  pull_request_target:
    types:
      - opened
    branches:
      - 'master'

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['master']
            })